### ISSUE TITLE
如果tls=false 怎么生成party_id

### ISSUE THREAD

**Issue by zhouyou9505** [secretflow/capsule-manager-sdk#8]
我开启的是仿真模式，启动--enable-tls false

现在 数据加密，需要生成party_id，不然上传秘钥失败

> alice获取自身的机构ID，机构ID是一个BASE32编码的客户端公钥的哈希值，可以用以下命令生成。
> cms_util generate-party-id --cert-pems-file alice.crt

由于我的我执行tls=false， 那么也没有alice.crt文件，如何执行cms_util generate-party-id --cert-pems-file alice.crt

**Comment by zhouaihui** [comment]
1. enable-tls表示和CapsuleManager之间的通信是否启用TLS。
2. 每个机构都应该都各自的私钥和证书，参考 https://www.secretflow.org.cn/docs/trustedflow/main/zh-Hans/architecture/principle

上述两件事是独立的，每个机构都需要生成证书和私钥，和enable-tls并无直接关联。
