### ISSUE TITLE
alice配置party id、证书、私钥、加密算法等。 报错

### ISSUE THREAD

**Issue by zhouyou9505** [secretflow/capsule-manager-sdk#9]
cms_config common --party-id BDEVTQ3U5WDPBGRLDPOIFIX7RV6MMUTI6DKAI4PX3733LYCC7BZA --scheme RSA 报错。解析yaml失败

Traceback (most recent call last):
`  File "/home/zhouyou/miniconda3/envs/tee/lib/python3.8/site-packages/yaml/constructor.py", line 218, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/home/zhouyou/miniconda3/envs/tee/lib/python3.8/site-packages/yaml/constructor.py", line 143, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/home/zhouyou/miniconda3/envs/tee/lib/python3.8/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/home/zhouyou/miniconda3/envs/tee/lib/python3.8/site-packages/yaml/constructor.py", line 427, in construct_undefined
    raise ConstructorError(None, None,
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/tuple'
  in "/home/zhouyou/miniconda3/envs/tee/lib/python3.8/site-packages/cli/cms/cli.yaml", line 10, column 18
`

此时打印cli.yaml   经过确认 （执行完config init 就是下面的情况）
cat cli/cms/cli.yaml
![image](https://github.com/secretflow/capsule-manager-sdk/assets/103442620/06cc87e4-e15c-4c9e-809e-efaf33bc0b67)
![image](https://github.com/secretflow/capsule-manager-sdk/assets/103442620/ac7de733-36c9-41d4-9655-d8bff23bab26)

**Comment by zhouyou9505** [comment]
目前是手动把   cert_chain_file: !!python/tuple       [ !!python/tuple]  这个给删除了。

**Comment by Chrisdehe** [comment]
与您提的[另一个issue](https://github.com/secretflow/capsule-manager-sdk/issues/10)是同样的问题，我们在[这里](https://github.com/secretflow/capsule-manager-sdk/issues/10)继续跟进
